name: Release lesson with tagged versions that uses tag format lessonXvX.Y.Z

on:
  workflow_call:

permissions:
  contents: write

jobs:
  release-lesson-version:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Release lesson ${{ github.ref_name }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}